package provision

import (
	"bytes"
	"fmt"
	"maps"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/adevmachine/cli/internal/config"
	"github.com/adevmachine/cli/internal/packages"
	agentskills "github.com/adevmachine/cli/internal/skills"
	"gopkg.in/yaml.v3"
)

// RemoteDir is where everything a run needs is unpacked on the machine.
const RemoteDir = "/opt/devmachine"

// inventoryHost is the one host in the generated inventory. It is a fixed name
// rather than the machine's own, so host_vars/<host>.yml has a path that does
// not move when a machine is renamed.
const inventoryHost = "devmachine"

// header says the file is generated, in the comment syntax both YAML and an
// INI-style config understand.
const header = "# Generated by devmachine. Every run rewrites it; do not edit.\n"

// The two directories roles are unpacked into. The operator's own copies come
// first in roles_path, and that ordering is the whole overlay mechanism.
const (
	releaseRoles = "roles"
	localRoles   = "roles.local"
)

// Generate returns the files Ansible needs, keyed by their path under
// RemoteDir.
//
// It is pure: the same plan gives the same bytes, so a change to what a
// machine is asked to do shows up as a diff rather than as a surprise.
func Generate(plan packages.MachinePlan) (map[string][]byte, error) {
	vars, err := hostVars(plan)
	if err != nil {
		return nil, err
	}
	site, err := playbook(plan)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"ansible.cfg":              []byte(ansibleCfg()),
		"inventory.ini":            []byte(inventory()),
		"host_vars/devmachine.yml": vars,
		"site.yml":                 []byte(site),
	}, nil
}

func ansibleCfg() string {
	return header + fmt.Sprintf(`[defaults]
roles_path = %[1]s/%[2]s:%[1]s/%[3]s
inventory = %[1]s/inventory.ini
host_key_checking = False
stdout_callback = default
`, RemoteDir, localRoles, releaseRoles)
}

// inventory names the one host and no group. A group of the same name would
// work, and Ansible warns about it on every run: "Found both group and host
// with same name". An ungrouped host is already in `all`, and `hosts:
// devmachine` matches it by name.
func inventory() string {
	return header + fmt.Sprintf("%s ansible_connection=local\n", inventoryHost)
}

// hostVars is what a recipe reads instead of the CLI's own configuration.
//
// The package list is what will run, not what was typed: a recipe asking
// whether a workspace has something wants the answer `needs` produced.
func hostVars(plan packages.MachinePlan) ([]byte, error) {
	type workspaceVars struct {
		Name     string   `yaml:"name"`
		User     string   `yaml:"user"`
		Packages []string `yaml:"packages"`
	}
	vars := struct {
		Machine    string          `yaml:"devmachine_machine"`
		Workspaces []workspaceVars `yaml:"devmachine_workspaces"`
	}{Machine: plan.Machine.Name, Workspaces: []workspaceVars{}}

	for _, workspace := range plan.Workspaces {
		vars.Workspaces = append(vars.Workspaces, workspaceVars{
			Name:     workspace.Target.Name,
			User:     workspace.Target.LinuxUser,
			Packages: names(workspace.Ordered),
		})
	}

	var root yaml.Node
	if err := root.Encode(vars); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	for _, found := range plan.OnMachine.Ordered {
		pairs, err := settingNodes(plan.Machine.Settings, found.Manifest.Name)
		if err != nil {
			return nil, err
		}
		root.Content = append(root.Content, pairs...)
	}

	var body bytes.Buffer
	body.WriteString("---\n" + header)
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(&root); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	return body.Bytes(), nil
}

// settingNodes names one package's settings the way its recipe already reads
// them: `devmachine_<package>_<key>`, which is the name its own
// defaults/main.yml gives the variable. A setting is a default somebody
// overrode, not a second mechanism, and the recipe cannot tell the difference.
func settingNodes(settings map[string]any, pkg string) ([]*yaml.Node, error) {
	values := config.SettingsFor(settings, pkg)
	named := make(map[string]string, len(values))
	for _, key := range slices.Sorted(maps.Keys(values)) {
		name := ansibleVariable(pkg + "." + key)
		if was, taken := named[name]; taken {
			return nil, fmt.Errorf(
				"the settings %q and %q are both the variable %s: rename one",
				pkg+"."+was, pkg+"."+key, name)
		}
		named[name] = key
	}

	var out []*yaml.Node
	for _, name := range slices.Sorted(maps.Keys(named)) {
		value := &yaml.Node{}
		if err := value.Encode(values[named[name]]); err != nil {
			return nil, fmt.Errorf("writing the setting %s: %w", name, err)
		}
		out = append(out, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: name}, value)
	}
	return out, nil
}

// varsBlock renders one package's settings as a task's own `vars:`.
//
// It is a task option and not one of include_role's: include_role takes a
// fixed set of options and refuses the whole play when it meets one it does
// not know.
func varsBlock(settings map[string]any, pkg string) (string, error) {
	lines, err := settingLines(settings, pkg, "        ")
	if err != nil || lines == "" {
		return "", err
	}
	return "      vars:\n" + lines, nil
}

// settingLines renders one package's settings as the body of a task's `vars:`
// block, indented to sit inside it.
func settingLines(settings map[string]any, pkg, indent string) (string, error) {
	pairs, err := settingNodes(settings, pkg)
	if err != nil {
		return "", err
	}
	if len(pairs) == 0 {
		return "", nil
	}

	var body bytes.Buffer
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(&yaml.Node{Kind: yaml.MappingNode, Tag: "!!map", Content: pairs}); err != nil {
		return "", fmt.Errorf("writing the settings of %s: %w", pkg, err)
	}
	if err := encoder.Close(); err != nil {
		return "", fmt.Errorf("writing the settings of %s: %w", pkg, err)
	}

	var out strings.Builder
	for _, line := range strings.Split(strings.TrimRight(body.String(), "\n"), "\n") {
		out.WriteString(indent + line + "\n")
	}
	return out.String(), nil
}

// ansibleVariable turns a setting's key into something Ansible accepts. A dash
// is fine in a package name and never fine in a variable; nor is the dot a
// package may use inside a key of its own.
func ansibleVariable(key string) string {
	return "devmachine_" + strings.NewReplacer("-", "_", ".", "_").Replace(key)
}

func playbook(plan packages.MachinePlan) (string, error) {
	var out strings.Builder
	out.WriteString("---\n" + header)
	fmt.Fprintf(&out, "- hosts: %s\n  become: true\n", inventoryHost)

	forWorkspaces, err := workspaceTasks(plan, false)
	if err != nil {
		return "", err
	}
	contributed, err := skillTasks(plan)
	if err != nil {
		return "", err
	}
	// The copies come after the packages that declared them: the account and
	// the tool both have to exist before a session is put where the tool
	// looks for it.
	shared, err := sharingTasks(plan)
	if err != nil {
		return "", err
	}
	tasks := machineTasks(plan) + forWorkspaces + contributed + shared
	// A package that READS a copied session sees nothing on the run that
	// delivered it, so a single pass would leave the machine needing another
	// `sync` — which is the one thing convergence must not do. The packages
	// are idempotent by contract, so the second pass costs a run that reports
	// no change except in whatever was waiting for the copy.
	if shared != "" {
		again, err := workspaceTasks(plan, true)
		if err != nil {
			return "", err
		}
		tasks += again
	}
	tasks += extensionTasks(plan)
	if tasks == "" {
		out.WriteString("  tasks: []\n")
		return out.String(), nil
	}
	out.WriteString("  tasks:\n")
	out.WriteString(tasks)
	return out.String(), nil
}

type contributedSkills struct {
	found      packages.Found
	skills     []agentskills.Skill
	workspaces []packages.Resolved
	claude     []packages.Resolved
}

// skillTasks converges package skill contributions for only the workspaces
// whose resolved package set includes the contributor.
func skillTasks(plan packages.MachinePlan) (string, error) {
	var contributions []contributedSkills
	byPackage := map[string]int{}
	for _, workspace := range plan.Workspaces {
		for _, found := range workspace.Ordered {
			if found.Manifest.Skills == nil {
				continue
			}
			index, ok := byPackage[found.Manifest.Name]
			if !ok {
				discovered, err := agentskills.Discover(filepath.Join(found.Manifest.Path, found.Manifest.Skills.Path))
				if err != nil {
					return "", fmt.Errorf("package %s skills: %w", found.Manifest.Name, err)
				}
				index = len(contributions)
				byPackage[found.Manifest.Name] = index
				contributions = append(contributions, contributedSkills{found: found, skills: discovered})
			}
			contributions[index].workspaces = append(contributions[index].workspaces, workspace)
			if has(workspace, "claude-code") {
				contributions[index].claude = append(contributions[index].claude, workspace)
			}
		}
	}

	var out strings.Builder
	for _, contribution := range contributions {
		writeSkillDirectories(&out, contribution)
		for _, skill := range contribution.skills {
			writeSkillConvergence(&out, contribution, skill)
		}
	}
	return out.String(), nil
}

func writeSkillDirectories(out *strings.Builder, contribution contributedSkills) {
	name := contribution.found.Manifest.Name
	for _, dir := range []struct {
		title string
		path  string
		mode  string
	}{
		{"canonical skill directory", "/home/{{ devmachine_workspace.user }}/.agents/skills", "0755"},
		{"skill ownership directory", "/home/{{ devmachine_workspace.user }}/.local/state/devmachine/skills", "0700"},
	} {
		fmt.Fprintf(out, "    - name: %s prepares the %s\n", name, dir.title)
		fmt.Fprintf(out, "      file:\n        path: %q\n        state: directory\n", dir.path)
		out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"{{ devmachine_workspace.user }}\"\n")
		fmt.Fprintf(out, "        mode: %q\n", dir.mode)
		writeSkillLoop(out, contribution.workspaces, false)
		fmt.Fprintf(out, "      tags: [%s]\n\n", name)
	}
	if len(contribution.claude) > 0 {
		fmt.Fprintf(out, "    - name: %s prepares the Claude skill directory\n", name)
		out.WriteString("      file:\n        path: \"/home/{{ devmachine_workspace.user }}/.claude/skills\"\n        state: directory\n")
		out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"{{ devmachine_workspace.user }}\"\n        mode: \"0755\"\n")
		writeSkillLoop(out, contribution.claude, false)
		fmt.Fprintf(out, "      tags: [%s]\n\n", name)
	}
}

func writeSkillConvergence(out *strings.Builder, contribution contributedSkills, skill agentskills.Skill) {
	pkg := contribution.found.Manifest.Name
	sourceID := pkg
	destination := "/home/{{ devmachine_workspace.user }}/.agents/skills/" + skill.Name
	owner := "/home/{{ devmachine_workspace.user }}/.local/state/devmachine/skills/" + skill.Name + ".owner"
	variable := strings.NewReplacer("-", "_", ".", "_").Replace(pkg + "_" + skill.Name)
	destinationResult := "devmachine_skill_" + variable + "_destination"
	ownerResult := "devmachine_skill_" + variable + "_owner"
	contentResult := "devmachine_skill_" + variable + "_owner_content"

	fmt.Fprintf(out, "    - name: %s checks the %s destination\n", pkg, skill.Name)
	fmt.Fprintf(out, "      stat:\n        path: %q\n", destination)
	fmt.Fprintf(out, "      register: %s\n", destinationResult)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s checks the %s ownership record\n", pkg, skill.Name)
	fmt.Fprintf(out, "      stat:\n        path: %q\n", owner)
	fmt.Fprintf(out, "      register: %s\n", ownerResult)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s reads the %s ownership record\n", pkg, skill.Name)
	fmt.Fprintf(out, "      slurp:\n        src: %q\n", owner)
	fmt.Fprintf(out, "      register: %s\n", contentResult)
	fmt.Fprintf(out, "      when: %s.results[devmachine_skill_index].stat.exists\n", ownerResult)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s refuses an unmanaged %s collision\n", pkg, skill.Name)
	fmt.Fprintf(out, "      fail:\n        msg: %q\n", "skill "+skill.Name+" already exists and is not owned by "+sourceID)
	out.WriteString("      when:\n")
	fmt.Fprintf(out, "        - %s.results[devmachine_skill_index].stat.exists\n", destinationResult)
	fmt.Fprintf(out, "        - not %s.results[devmachine_skill_index].stat.exists or ((%s.results[devmachine_skill_index].content | default('') | b64decode | trim) != %q)\n", ownerResult, contentResult, sourceID)
	writeSkillLoop(out, contribution.workspaces, true)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s installs the %s skill\n", pkg, skill.Name)
	fmt.Fprintf(out, "      copy:\n        src: %q\n        dest: %q\n", RolePath(contribution.found.Source, pkg, contribution.found.Manifest.Skills.Path, skill.Name)+"/", destination+"/")
	out.WriteString("        remote_src: true\n        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"{{ devmachine_workspace.user }}\"\n        mode: preserve\n")
	writeSkillLoop(out, contribution.workspaces, false)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	fmt.Fprintf(out, "    - name: %s records ownership of the %s skill\n", pkg, skill.Name)
	fmt.Fprintf(out, "      copy:\n        content: %q\n        dest: %q\n", sourceID+"\n", owner)
	out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"{{ devmachine_workspace.user }}\"\n        mode: \"0600\"\n")
	writeSkillLoop(out, contribution.workspaces, false)
	fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)

	if len(contribution.claude) > 0 {
		fmt.Fprintf(out, "    - name: %s links the %s skill for Claude\n", pkg, skill.Name)
		fmt.Fprintf(out, "      file:\n        src: %q\n        dest: %q\n        state: link\n", "../../.agents/skills/"+skill.Name, "/home/{{ devmachine_workspace.user }}/.claude/skills/"+skill.Name)
		out.WriteString("        owner: \"{{ devmachine_workspace.user }}\"\n        group: \"{{ devmachine_workspace.user }}\"\n")
		writeSkillLoop(out, contribution.claude, false)
		fmt.Fprintf(out, "      tags: [%s]\n\n", pkg)
	}
}

func writeSkillLoop(out *strings.Builder, workspaces []packages.Resolved, indexed bool) {
	out.WriteString("      loop:\n")
	for _, workspace := range workspaces {
		fmt.Fprintf(out, "        - {name: %q, user: %q}\n", workspace.Target.Name, workspace.Target.LinuxUser)
	}
	out.WriteString("      loop_control:\n        loop_var: devmachine_workspace\n")
	if indexed {
		out.WriteString("        index_var: devmachine_skill_index\n")
	}
}

func machineTasks(plan packages.MachinePlan) string {
	var out strings.Builder
	for _, found := range plan.OnMachine.Ordered {
		name := found.Manifest.Name
		fmt.Fprintf(&out, "    - name: %s\n", name)
		out.WriteString(includeRole(name))
		fmt.Fprintf(&out, "      tags: [%s]\n\n", name)
	}
	return out.String()
}

// workspaceTasks runs each workspace package once, looping over the
// workspaces that asked for it.
//
// The packages are ordered by walking the workspaces in turn and taking each
// name the first time it appears. That keeps `needs` satisfied: a package is
// always preceded by what it needs inside every workspace that has it, so the
// first appearance of a need is never later than the first appearance of the
// package that needs it.
func workspaceTasks(plan packages.MachinePlan, again bool) (string, error) {
	var (
		out   strings.Builder
		order []string
		seen  = map[string]bool{}
	)
	for _, workspace := range plan.Workspaces {
		for _, found := range workspace.Ordered {
			if name := found.Manifest.Name; !seen[name] {
				seen[name] = true
				order = append(order, name)
			}
		}
	}

	for _, name := range order {
		groups, err := groupBySettings(plan, name)
		if err != nil {
			return "", err
		}
		for _, group := range groups {
			fmt.Fprintf(&out, "    - name: %s\n", group.title(name, again))
			out.WriteString(includeRole(name))
			out.WriteString(group.vars)
			out.WriteString("      loop:\n")
			for _, workspace := range group.workspaces {
				fmt.Fprintf(&out, "        - {name: %q, user: %q}\n",
					workspace.Target.Name, workspace.Target.LinuxUser)
			}
			// loop_var, rather than `vars: devmachine_workspace: "{{ item }}"`.
			// A role is free to have loops of its own, and any of them would
			// rebind `item` — so the workspace would quietly become whatever
			// the inner loop was iterating. Naming the variable here means no
			// package can get it wrong, and none has to remember to try.
			out.WriteString("      loop_control:\n        loop_var: devmachine_workspace\n")
			fmt.Fprintf(&out, "      tags: [%s]\n\n", name)
		}
	}
	return out.String(), nil
}

// group is the workspaces one include_role covers: those that give a package
// the same settings, which is usually all of them and no settings at all.
type group struct {
	vars       string
	workspaces []packages.Resolved
}

func (g group) title(pkg string, again bool) string {
	if again {
		return pkg + " again, now that the shared logins are in place"
	}
	if g.vars == "" {
		return pkg + " for each workspace that declares it"
	}
	who := make([]string, 0, len(g.workspaces))
	for _, workspace := range g.workspaces {
		who = append(who, workspace.Target.Name)
	}
	return pkg + " for " + strings.Join(who, ", ")
}

// groupBySettings splits the workspaces that install a package by what they
// set on it, in the order they appear. One loop cannot carry two values for
// one variable, so a workspace that overrides something gets a task of its
// own; everybody else keeps sharing one.
func groupBySettings(plan packages.MachinePlan, pkg string) ([]group, error) {
	var (
		groups []group
		at     = map[string]int{}
	)
	for _, workspace := range plan.Workspaces {
		if !has(workspace, pkg) {
			continue
		}
		vars, err := varsBlock(workspace.Target.Settings, pkg)
		if err != nil {
			return nil, fmt.Errorf("workspace %q: %w", workspace.Target.Name, err)
		}
		index, known := at[vars]
		if !known {
			index = len(groups)
			at[vars] = index
			groups = append(groups, group{vars: vars})
		}
		groups[index].workspaces = append(groups[index].workspaces, workspace)
	}
	return groups, nil
}

// extensionTasks copy each contribution into the directory its provider
// opened. They run last, after the package that creates the directory.
func extensionTasks(plan packages.MachinePlan) string {
	found := map[string]packages.Found{}
	for _, resolved := range append([]packages.Resolved{plan.OnMachine}, plan.Workspaces...) {
		for _, f := range resolved.Ordered {
			found[f.Manifest.Name] = f
		}
	}

	var out strings.Builder
	for _, extension := range plan.Extensions {
		from := found[extension.From]
		source := path.Join(RemoteDir, rolesDir(from.Source), extension.From, extension.Source)

		// The destination is named after what contributed it, so two packages
		// shipping the same file name cannot collide. The workspace is in the
		// name too, or the same package installed for two people would have
		// one of them quietly overwrite the other.
		destination := extension.From + "-" + path.Base(extension.Source)
		where := extension.Point
		if from.Manifest.Scope == packages.ScopeWorkspace {
			destination = extension.Target + "-" + destination
			where += " for " + extension.Target
		}

		fmt.Fprintf(&out, "    - name: %s extends %s\n", extension.From, where)
		fmt.Fprintf(&out, "      copy:\n        src: %q\n        dest: %q\n",
			source, path.Join(extension.Into, destination))
		out.WriteString("        owner: root\n        group: root\n        mode: \"0644\"\n")
		fmt.Fprintf(&out, "      tags: [%s]\n\n", extension.From)
	}
	return out.String()
}

// includeRole is a dynamic include, and the apply block is not optional:
// without it the role's own tasks do not inherit the tag, so `--tags docker`
// includes the role and then skips everything in it.
func includeRole(name string) string {
	return fmt.Sprintf("      include_role:\n        name: %s\n        apply:\n          tags: [%s]\n",
		name, name)
}

// RolePath names a file inside a package, on the machine.
//
// It is exported because the CLI reaches into a package from outside this
// package — a DNS provider's entrypoint, a credential's helper — and the
// overlay rule that picks roles.local over roles must have exactly one
// implementation. Two would be one rule nobody remembers to change twice.
func RolePath(source, name string, rest ...string) string {
	return path.Join(append([]string{RemoteDir, rolesDir(source), name}, rest...)...)
}

// rolesDir is where a package is unpacked, which is what decides whether the
// operator's copy or the published one runs.
func rolesDir(source string) string {
	if source == packages.SourceLocal {
		return localRoles
	}
	return releaseRoles
}

func has(resolved packages.Resolved, name string) bool {
	for _, found := range resolved.Ordered {
		if found.Manifest.Name == name {
			return true
		}
	}
	return false
}

func names(found []packages.Found) []string {
	out := make([]string, 0, len(found))
	for _, f := range found {
		out = append(out, f.Manifest.Name)
	}
	return out
}
