package provision

import (
	"bytes"
	"fmt"
	"path"
	"strings"

	"github.com/adevmachine/cli/internal/packages"
	"gopkg.in/yaml.v3"
)

// RemoteDir is where everything a run needs is unpacked on the machine.
const RemoteDir = "/opt/devmachine"

// inventoryHost is the one host in the generated inventory. It is a fixed name
// rather than the machine's own, so host_vars/<host>.yml has a path that does
// not move when a machine is renamed.
const inventoryHost = "devmachine"

// header says the file is generated, in the comment syntax both YAML and an
// INI-style config understand.
const header = "# Generated by devmachine. Every run rewrites it; do not edit.\n"

// The two directories roles are unpacked into. The operator's own copies come
// first in roles_path, and that ordering is the whole overlay mechanism.
const (
	releaseRoles = "roles"
	localRoles   = "roles.local"
)

// Generate returns the files Ansible needs, keyed by their path under
// RemoteDir.
//
// It is pure: the same plan gives the same bytes, so a change to what a
// machine is asked to do shows up as a diff rather than as a surprise.
func Generate(plan packages.MachinePlan) (map[string][]byte, error) {
	vars, err := hostVars(plan)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"ansible.cfg":              []byte(ansibleCfg()),
		"inventory.ini":            []byte(inventory()),
		"host_vars/devmachine.yml": vars,
		"site.yml":                 []byte(playbook(plan)),
	}, nil
}

func ansibleCfg() string {
	return header + fmt.Sprintf(`[defaults]
roles_path = %[1]s/%[2]s:%[1]s/%[3]s
inventory = %[1]s/inventory.ini
host_key_checking = False
stdout_callback = default
`, RemoteDir, localRoles, releaseRoles)
}

// inventory names the one host and no group. A group of the same name would
// work, and Ansible warns about it on every run: "Found both group and host
// with same name". An ungrouped host is already in `all`, and `hosts:
// devmachine` matches it by name.
func inventory() string {
	return header + fmt.Sprintf("%s ansible_connection=local\n", inventoryHost)
}

// hostVars is what a recipe reads instead of the CLI's own configuration.
//
// The package list is what will run, not what was typed: a recipe asking
// whether a workspace has something wants the answer `needs` produced.
func hostVars(plan packages.MachinePlan) ([]byte, error) {
	type workspaceVars struct {
		Name     string   `yaml:"name"`
		User     string   `yaml:"user"`
		Packages []string `yaml:"packages"`
	}
	vars := struct {
		Machine    string          `yaml:"devmachine_machine"`
		Workspaces []workspaceVars `yaml:"devmachine_workspaces"`
	}{Machine: plan.Machine.Name, Workspaces: []workspaceVars{}}

	for _, workspace := range plan.Workspaces {
		vars.Workspaces = append(vars.Workspaces, workspaceVars{
			Name:     workspace.Target.Name,
			User:     workspace.Target.LinuxUser,
			Packages: names(workspace.Ordered),
		})
	}

	var body bytes.Buffer
	body.WriteString("---\n" + header)
	encoder := yaml.NewEncoder(&body)
	encoder.SetIndent(2)
	if err := encoder.Encode(vars); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	if err := encoder.Close(); err != nil {
		return nil, fmt.Errorf("writing the host variables: %w", err)
	}
	return body.Bytes(), nil
}

func playbook(plan packages.MachinePlan) string {
	var out strings.Builder
	out.WriteString("---\n" + header)
	fmt.Fprintf(&out, "- hosts: %s\n  become: true\n", inventoryHost)

	tasks := machineTasks(plan) + workspaceTasks(plan) + extensionTasks(plan)
	if tasks == "" {
		out.WriteString("  tasks: []\n")
		return out.String()
	}
	out.WriteString("  tasks:\n")
	out.WriteString(tasks)
	return out.String()
}

func machineTasks(plan packages.MachinePlan) string {
	var out strings.Builder
	for _, found := range plan.OnMachine.Ordered {
		name := found.Manifest.Name
		fmt.Fprintf(&out, "    - name: %s\n", name)
		out.WriteString(includeRole(name))
		fmt.Fprintf(&out, "      tags: [%s]\n\n", name)
	}
	return out.String()
}

// workspaceTasks runs each workspace package once, looping over the
// workspaces that asked for it.
//
// The packages are ordered by walking the workspaces in turn and taking each
// name the first time it appears. That keeps `needs` satisfied: a package is
// always preceded by what it needs inside every workspace that has it, so the
// first appearance of a need is never later than the first appearance of the
// package that needs it.
func workspaceTasks(plan packages.MachinePlan) string {
	var (
		out   strings.Builder
		order []string
		seen  = map[string]bool{}
	)
	for _, workspace := range plan.Workspaces {
		for _, found := range workspace.Ordered {
			if name := found.Manifest.Name; !seen[name] {
				seen[name] = true
				order = append(order, name)
			}
		}
	}

	for _, name := range order {
		fmt.Fprintf(&out, "    - name: %s for each workspace that declares it\n", name)
		out.WriteString(includeRole(name))
		out.WriteString("      vars:\n        devmachine_workspace: \"{{ item }}\"\n      loop:\n")
		for _, workspace := range plan.Workspaces {
			if !has(workspace, name) {
				continue
			}
			fmt.Fprintf(&out, "        - {name: %q, user: %q}\n",
				workspace.Target.Name, workspace.Target.LinuxUser)
		}
		fmt.Fprintf(&out, "      tags: [%s]\n\n", name)
	}
	return out.String()
}

// extensionTasks copy each contribution into the directory its provider
// opened. They run last, after the package that creates the directory.
func extensionTasks(plan packages.MachinePlan) string {
	found := map[string]packages.Found{}
	for _, resolved := range append([]packages.Resolved{plan.OnMachine}, plan.Workspaces...) {
		for _, f := range resolved.Ordered {
			found[f.Manifest.Name] = f
		}
	}

	var out strings.Builder
	for _, extension := range plan.Extensions {
		from := found[extension.From]
		source := path.Join(RemoteDir, rolesDir(from.Source), extension.From, extension.Source)

		// The destination is named after what contributed it, so two packages
		// shipping the same file name cannot collide. The workspace is in the
		// name too, or the same package installed for two people would have
		// one of them quietly overwrite the other.
		destination := extension.From + "-" + path.Base(extension.Source)
		where := extension.Point
		if from.Manifest.Scope == packages.ScopeWorkspace {
			destination = extension.Target + "-" + destination
			where += " for " + extension.Target
		}

		fmt.Fprintf(&out, "    - name: %s extends %s\n", extension.From, where)
		fmt.Fprintf(&out, "      copy:\n        src: %q\n        dest: %q\n",
			source, path.Join(extension.Into, destination))
		out.WriteString("        owner: root\n        group: root\n        mode: \"0644\"\n")
		fmt.Fprintf(&out, "      tags: [%s]\n\n", extension.From)
	}
	return out.String()
}

// includeRole is a dynamic include, and the apply block is not optional:
// without it the role's own tasks do not inherit the tag, so `--tags docker`
// includes the role and then skips everything in it.
func includeRole(name string) string {
	return fmt.Sprintf("      include_role:\n        name: %s\n        apply:\n          tags: [%s]\n",
		name, name)
}

// rolesDir is where a package is unpacked, which is what decides whether the
// operator's copy or the published one runs.
func rolesDir(source string) string {
	if source == packages.SourceLocal {
		return localRoles
	}
	return releaseRoles
}

func has(resolved packages.Resolved, name string) bool {
	for _, found := range resolved.Ordered {
		if found.Manifest.Name == name {
			return true
		}
	}
	return false
}

func names(found []packages.Found) []string {
	out := make([]string, 0, len(found))
	for _, f := range found {
		out = append(out, f.Manifest.Name)
	}
	return out
}
